njaard/libavif-rs

Cargo.toml
First of all, thanks for making this. I'm also interested in working with libavif in Rust and your crates made it so I won't have to do everything from scratch.
This PR makes libavif-image and libavif-sys [workspace members](https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) of libavif
=> Make libavif-{image,sys} workspace members of libavif

libavif-image/Cargo.toml
This will allow top level crates to depend only on a subset of features from the image crate
=> Disable default features for the image crate

Cargo.toml, libavif-image/Cargo.toml, libavif-sys/Cargo.toml, libavif-sys/build.rs
This allows changing libavif-sys features from libavif and libavif-image, which wasn't possible before since libavif imported libavif-sys with default features enabled.
This change should also [fix builds on docs.rs](https://docs.rs/crate/libavif-sys/0.4.0/builds/222959) by compiling using aom, since the dependencies necessary to build dav1d aren't available there. I added an hidden feature named `__internal_aom_generic_target`, telling aom to compile without cpu target optimizations, since nasm is also missing from the docs.rs build environment.
=> Allow changing codec from libavif and libavif-image | Fix docs.rs build

examples/png2avif.rs, libavif-image/src/lib.rs, libavif-image/tests/check.rs, src/data.rs, src/lib.rs
Creates a safe wrapper around avifRWData and uses it to return the encoded avif image bytes.
This avoids having to call .to_vec() to get the bytes returned by the encoder, which avoids copying data.
=> Avoid copying the encoded image bytes when returning them

examples/png2avif.rs, libavif-image/src/lib.rs, src/lib.rs
This changes the encoder to use the already allocated pixels passed by the caller instead of allocating new avifRGBImage pixels
=> encoder: reuse the caller's allocated pixels

libavif-sys/src/lib.rs, src/lib.rs
This will be a breaking change. We can wait to merge this if you plan to release other patch versions, this libavif release doesn't seem to change anything we expose through the `libavif` crate.
[libavif changelog](https://github.com/AOMediaCodec/libavif/blob/master/CHANGELOG.md#080---2020-07-14)
=> Update libavif to v0.8.0, libaom to v2.0.0 and dav1d v0.7.1

libavif-image/src/lib.rs
`libavif` already accepts RGBA images so this just adds support to `libavif-image`
=> Add DynamicImage::ImageRgba8 support to libavif-image

libavif-image/tests/check.rs
This improves #5 by trying to compare the original image to the one which went through the encoder and the decoder and checking that the difference isn't too big between the two.
=> tests: verify that the decoded avif matches the original image

examples/avif2png.rs, libavif-image/src/lib.rs, src/image.rs, src/lib.rs
This is the first step into extending the encoder and decoder to make them accept all or at least most color formats the libavif library already accepts.
=> feat: add to and from slice conversions to RgbPixels

.gitmodules, Cargo.toml, libaom-sys/Cargo.toml, libaom-sys/build.rs, libaom-sys/src/lib.rs, libavif-image/Cargo.toml, libavif-sys/Cargo.toml, libavif-sys/build.rs, libavif-sys/src/lib.rs
It makes the crate smaller for people who don't use libaom. Helps Cargo build more crates in parallel if aom is used.
=> Separate out libaom build

Cargo.toml, libaom-sys/build.rs, libavif-image/Cargo.toml, libavif-sys/Cargo.toml, libavif-sys/build.rs
I've checked that it doesn't affect `cargo test --doc`
=> No need to link when generating docs

libaom-sys/Cargo.toml, libavif-sys/Cargo.toml
Makes crate tarballs marginally smaller. I couldn't exclude anything from dav1d, because meson is guarding it too tightly.
=> Exclude unused files

libavif-sys/build.rs
Updates libavif.
New version has an option to disable `-Werror`, which is necessary to make builds reliable. Otherwise it didn't compile with Apple clang 12, which introduced a new warning that wasn't relevant to libavif at all, but still broke the build, since libavif enabled all warnings for everything and `-Werror`.
=> Make libavif builds less fragile

src/image.rs, src/lib.rs
While working on the previous PR I realized `avifImage` doesn't get freed if decoding fails.
Checking out the code in more detail it isn't as bad as I initially thought of, since the planes [get copied into our `avifImage`](https://github.com/AOMediaCodec/libavif/blob/e50032305454cabd8d9466ffb6f2f84f2f3d10c2/src/read.c#L2735) only after decoding succeeds. However [avifImage itself is heap allocated](https://github.com/AOMediaCodec/libavif/blob/3e735b860a1f1b7b6e3c5ff2777caf29f233e494/src/avif.c#L109-L123), so we would still be leaking some memory by not freeing it.
This implementation avoids creating an `avifImage` directly and instead creates an `AvifImage`, which freezes the underlying avifImage as soon as it's dropped.
=> Make sure to destroy avifImage if decoding fails

.github/workflows/ci.yml, README.md, libavif-image/README.md, libavif-sys/Cargo.toml, libavif-sys/README.md
Changes: https://github.com/xiph/rav1e/releases/tag/v0.4.0-alpha
=> Begin testing with rav1e v0.4.0-alpha

libaom-sys/build.rs, libavif-sys/build.rs
#24 has been [fixed by upstream](https://aomedia.googlesource.com/aom/+/29dd4e20cd6544a5a2f123736a01a720496e02ff) so the [original workaround](https://github.com/njaard/libavif-rs/commit/6c7ff4bf2219c4bcfe6796183e7c197398c94987) became unnecessary, and it's somehow not working on my machine:
```
running: "cmake" "libavif-rs/libavif-sys/libavif" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DBUILD_SHARED_LIBS=0" "-DAVIF_ENABLE_WERROR=0" "-DAVIF_CODEC_AOM=1" "-DAOM_INCLUDE_DIR=libavif-rs/libaom-sys/vendor" "-DCMAKE_PREFIX_PATH=" "-DCMAKE_INSTALL_PREFIX=libavif-rs/target/debug/build/libavif-sys-6d57f1058e9a9e31/out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD …
```
=> Fix MSVC build failure with `libaom`

libaom-sys/build.rs
On my void linux install, it appears that `CMAKE_INSTALL_LIBDIR` defaults to `lib64`, which breaks libaom-sys, since it's looking for the static library in `lib`.
It looks like we're already overriding `CMAKE_INSTALL_LIBDIR` for `libavif-sys`, so we can just use the same pattern here.
=> override CMAKE_INSTALL_LIBDIR for libaom

src/encoder.rs
splitting `max/min` quantizer is really useful. For example, encoding https://nextjs.org/showcase/hulu with quantizer `max: 50` `min: 25` is almost the same as `max: 50` `min:50`, but 2x faster.
=> Split max/min quantizer settings for Encoder

libavif-sys/Cargo.toml
libavif-sys build can fail with:
```markdown
error[E0599]: no method named `configure_arg` found for struct `Config` in the current scope
--> ~/.cargo/registry/src/github.com-1ecc6299db9ec823/libavif-sys-0.13.1/build.rs:90:14
|
90 |         avif.configure_arg("-T host=x64").configure_arg("-A Win32");
|              ^^^^^^^^^^^^^ method not found in `Config`
```
due to allowing semver-incompatible **older** versions of cmake.
=> Fix cmake version

libavif-sys/build.rs, libdav1d-sys/build.rs, libdav1d-sys/wasm32-unknown-emscripten.meson
Can't build `libavif-sys` with `rav1e` + `dav1d` to `wasm32-unknown-emscripten`.
This should fix it.
=> Fix wasm32-unknown-emscripten build problems

libaom-sys/Cargo.toml, libavif-sys/Cargo.toml, libdav1d-sys/Cargo.toml
I think this change would make it a bit more obvious to external users what version of the underlying vendored C library they're getting from crates.io.
Many other crates do this, for example [`zstd-sys`](https://crates.io/crates/zstd-sys/2.0.9+zstd.1.5.5)
=> Use SemVer Build Metadata to convey the version of the underlying library

libdav1d-sys/Cargo.toml, libdav1d-sys/ffi.rs
Changelog: https://code.videolan.org/videolan/dav1d/-/releases/1.4.2
=> Bump libdav1d to v1.4.2

libdav1d-sys/build.rs, libdav1d-sys/x86_64-w64-mingw32.meson
The cross compile target for compiling windows x86_64 on linux using mingw for libdav1d was missing.
This pull request adds it so that a library that uses libavif-rs as a dependency and wants to cross compile to windows on linux can do so without the build failing to link.
The meson config for mingw32 w64 was taken directly from the videolan repository for libdav1d.
=> add x86_64-w64-mingw32 target to libdav1d-sys

.github/workflows/ci.yml, libaom-sys/build.rs
Blindly applying the rename in https://doc.rust-lang.org/rustc/platform-support/wasm32-wasip1-threads.html to see if it fixes the rav1e CI
=> Apply wasm32-wasi-preview1-threads to wasm32-wasip1-threads rename
